"""
Data structures for strategy selection.

Defines the core types used by the problem analyzer and strategy selector
to classify problems, generate recommendations, and record decisions.
"""

from dataclasses import dataclass, field, asdict
from typing import Any


# Valid problem types
PROBLEM_TYPES = frozenset({
    "new_algorithm",     # Create something from scratch
    "tune_existing",     # Optimize parameters of existing code
    "stuck_evolution",   # Evolution has plateaued, need new approach
    "hybrid",            # Combination of code and parameter optimization
})

# Valid strategy types
STRATEGY_TYPES = frozenset({
    "code_evolution",           # Evolve algorithm code
    "hyperparameter_evolution", # Optimize numeric parameters
    "hybrid",                   # Both code and parameter evolution
})

# Valid complexity levels
COMPLEXITY_LEVELS = frozenset({
    "simple",   # Few parameters, straightforward objective
    "medium",   # Moderate parameters or multi-objective
    "complex",  # Many parameters, complex interactions
})


@dataclass
class DetectedParameter:
    """A tunable parameter detected in code.

    Represents a single numeric or categorical parameter found during
    code analysis that could be optimized.

    Args:
        name: Parameter name as it appears in code.
        value: Current default value.
        location: Where in the code this was found (e.g., "MyClass.__init__").
        param_type: Type of parameter ("int", "float", "bool", "categorical").
        description: Brief description of what this parameter controls.
    """
    name: str
    value: Any
    location: str
    param_type: str = "float"
    description: str = ""

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary for storage."""
        return asdict(self)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "DetectedParameter":
        """Create from dictionary."""
        return cls(**data)


@dataclass
class ProblemContext:
    """Context about the problem being solved.

    Produced by ProblemAnalyzer.analyze() to capture everything known about
    the user's problem, including detected parameters and historical data.

    Args:
        problem_type: Classification of the problem. One of PROBLEM_TYPES.
        has_parameters: Whether tunable parameters were detected in the code.
        detected_parameters: List of detected tunable parameters.
        complexity: Estimated problem complexity. One of COMPLEXITY_LEVELS.
        similar_past_runs: Memory frames from similar past problems.
        is_continuation: Whether this continues a previous evolution run.
        user_prompt: The original user prompt.
        keywords: Extracted keywords for memory lookups.
    """
    problem_type: str
    has_parameters: bool
    detected_parameters: list[DetectedParameter] = field(default_factory=list)
    complexity: str = "medium"
    similar_past_runs: list[Any] = field(default_factory=list)
    is_continuation: bool = False
    user_prompt: str = ""
    keywords: list[str] = field(default_factory=list)

    def __post_init__(self) -> None:
        """Validate fields after initialization."""
        if self.problem_type not in PROBLEM_TYPES:
            raise ValueError(
                f"Invalid problem_type '{self.problem_type}'. "
                f"Must be one of: {sorted(PROBLEM_TYPES)}"
            )
        if self.complexity not in COMPLEXITY_LEVELS:
            raise ValueError(
                f"Invalid complexity '{self.complexity}'. "
                f"Must be one of: {sorted(COMPLEXITY_LEVELS)}"
            )

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary for storage."""
        d = asdict(self)
        d["detected_parameters"] = [p.to_dict() for p in self.detected_parameters]
        return d

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "ProblemContext":
        """Create from dictionary."""
        data = data.copy()
        params = data.pop("detected_parameters", [])
        ctx = cls(**data)
        ctx.detected_parameters = [DetectedParameter.from_dict(p) for p in params]
        return ctx


@dataclass
class StrategyRecommendation:
    """A recommended strategy with confidence score.

    Generated by the strategy selector, ranked by confidence.

    Args:
        strategy: The recommended strategy. One of STRATEGY_TYPES.
        confidence: Confidence score from 0.0 to 1.0.
        reason: Human-readable explanation of why this strategy is recommended.
        memory_enhanced: Whether this recommendation was boosted by historical data.
    """
    strategy: str
    confidence: float
    reason: str
    memory_enhanced: bool = False

    def __post_init__(self) -> None:
        """Validate fields after initialization."""
        if self.strategy not in STRATEGY_TYPES:
            raise ValueError(
                f"Invalid strategy '{self.strategy}'. "
                f"Must be one of: {sorted(STRATEGY_TYPES)}"
            )
        if not 0.0 <= self.confidence <= 1.0:
            raise ValueError(
                f"Confidence must be between 0.0 and 1.0, got {self.confidence}"
            )

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary for storage."""
        return asdict(self)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "StrategyRecommendation":
        """Create from dictionary."""
        return cls(**data)


@dataclass
class StrategyDecision:
    """Final strategy decision after user confirmation.

    Records which strategy was chosen, how it was selected, and the
    full context for memory storage and future learning.

    Args:
        strategy: The chosen strategy. One of STRATEGY_TYPES.
        auto_selected: Whether this was auto-selected without user input.
        user_confirmed: Whether the user explicitly confirmed this choice.
        recommendations: The full list of recommendations that were presented.
        context: The problem context that led to this decision.
    """
    strategy: str
    auto_selected: bool = False
    user_confirmed: bool = False
    recommendations: list[StrategyRecommendation] = field(default_factory=list)
    context: ProblemContext | None = None

    def __post_init__(self) -> None:
        """Validate fields after initialization."""
        if self.strategy not in STRATEGY_TYPES:
            raise ValueError(
                f"Invalid strategy '{self.strategy}'. "
                f"Must be one of: {sorted(STRATEGY_TYPES)}"
            )

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary for storage."""
        d = {
            "strategy": self.strategy,
            "auto_selected": self.auto_selected,
            "user_confirmed": self.user_confirmed,
            "recommendations": [r.to_dict() for r in self.recommendations],
        }
        if self.context is not None:
            d["context"] = self.context.to_dict()
        return d

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "StrategyDecision":
        """Create from dictionary."""
        data = data.copy()
        recs = data.pop("recommendations", [])
        ctx_data = data.pop("context", None)
        decision = cls(**data)
        decision.recommendations = [StrategyRecommendation.from_dict(r) for r in recs]
        if ctx_data is not None:
            decision.context = ProblemContext.from_dict(ctx_data)
        return decision
